# Generated by Django 4.2.2 on 2023-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
