# Generated by Django 4.2.2 on 2023-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=5),
        ),
    ]
